In [1]:
# %%
import pandas as pd
import plotly.express as px

telemetriadados = pd.read_csv("rocket_telemetry_dataset.csv")
display (telemetriadados)
telemetriadados1 = telemetriadados[telemetriadados["Mission_ID"] == "M-001"]
telemetriadados2 = telemetriadados[telemetriadados ["Mission_ID"] == "M-002"]
telemetriadados3 = telemetriadados [telemetriadados ["Mission_ID"] == "M-003"]
display (telemetriadados1)
display (telemetriadados2)
display (telemetriadados3)

,Time,Altitude,Velocity,Accel,Mass,Dyn. Pressure,Mach,Atm. Pressure,Stag. Temp,Flight_Type,Mission_ID
0,0.0,0.00,0.00,0.80,421300.00,0.00,0.0000,101325.00,288.15,Heavy_Lift_Standard,M-001
1,1.0,3.95,7.93,0.82,417934.01,38.48,0.0233,101277.53,288.16,Heavy_Lift_Standard,M-001
2,2.0,15.90,16.00,0.83,414568.74,156.53,0.0470,101134.10,288.17,Heavy_Lift_Standard,M-001
3,3.0,36.00,24.21,0.85,411204.91,357.90,0.0712,100893.31,288.21,Heavy_Lift_Standard,M-001
4,4.0,64.38,32.58,0.86,407843.26,646.07,0.0958,100553.96,288.26,Heavy_Lift_Standard,M-001
...,...,...,...,...,...,...,...,...,...,...,...
2423,119.0,1921.49,445.20,0.85,308013.14,100535.19,1.3376,80272.96,374.30,Early_Engine_Shutdown,M-003
2424,120.0,1475.80,453.38,0.84,308013.14,109007.35,1.3551,84807.22,380.86,Early_Engine_Shutdown,M-003
2425,121.0,1021.90,461.43,0.82,308013.14,118093.09,1.3719,89635.92,387.47,Early_Engine_Shutdown,M-003
2426,122.0,559.93,469.35,0.81,308013.14,127825.13,1.3881,94776.73,394.14,Early_Engine_Shutdown,M-003
2427,123.0,90.03,477.13,0.79,308013.14,138236.23,1.4035,100248.14,400.86,Early_Engine_Shutdown,M-003

,Time,Altitude,Velocity,Accel,Mass,Dyn. Pressure,Mach,Atm. Pressure,Stag. Temp,Flight_Type,Mission_ID
0,0.0,0.00,0.00,0.80,421300.00,0.00,0.0000,101325.00,288.15,Heavy_Lift_Standard,M-001
1,1.0,3.95,7.93,0.82,417934.01,38.48,0.0233,101277.53,288.16,Heavy_Lift_Standard,M-001
2,2.0,15.90,16.00,0.83,414568.74,156.53,0.0470,101134.10,288.17,Heavy_Lift_Standard,M-001
3,3.0,36.00,24.21,0.85,411204.91,357.90,0.0712,100893.31,288.21,Heavy_Lift_Standard,M-001
4,4.0,64.38,32.58,0.86,407843.26,646.07,0.0958,100553.96,288.26,Heavy_Lift_Standard,M-001
...,...,...,...,...,...,...,...,...,...,...,...
1996,1996.0,1776351.04,3965.36,0.61,25506.96,0.00,0.0000,0.00,216.65,Heavy_Lift_Standard,M-001
1997,1997.0,1772834.62,3970.69,0.61,25506.96,0.00,0.0000,0.00,216.65,Heavy_Lift_Standard,M-001
1998,1998.0,1769312.61,3976.02,0.61,25506.96,0.00,0.0000,0.00,216.65,Heavy_Lift_Standard,M-001
1999,1999.0,1765785.00,3981.35,0.61,25506.96,0.00,0.0000,0.00,216.65,Heavy_Lift_Standard,M-001
2000,2000.0,1762251.78,3986.69,0.61,25506.96,0.00,0.0000,0.00,216.65,Heavy_Lift_Standard,M-001

,Time,Altitude,Velocity,Accel,Mass,Dyn. Pressure,Mach,Atm. Pressure,Stag. Temp,Flight_Type,Mission_ID
2001,0.0,0.00,0.00,1.79,85600.00,0.00,0.0000,101325.00,288.15,Sounding_Rocket,M-002
2002,1.0,8.82,17.69,1.82,84542.33,191.44,0.0520,101219.15,288.25,Sounding_Rocket,M-002
2003,2.0,35.48,35.71,1.85,83485.06,778.37,0.1050,100899.44,288.55,Sounding_Rocket,M-002
2004,3.0,80.34,54.07,1.89,82428.59,1776.64,0.1590,100363.51,289.08,Sounding_Rocket,M-002
2005,4.0,143.73,72.75,1.92,81373.32,3197.48,0.2141,99610.25,289.85,Sounding_Rocket,M-002
...,...,...,...,...,...,...,...,...,...,...,...
2299,298.0,4128.83,942.18,3.07,41224.11,358652.83,2.9074,60612.02,703.09,Sounding_Rocket,M-002
2300,299.0,3205.55,911.49,3.19,41224.11,369725.66,2.7810,68294.95,680.78,Sounding_Rocket,M-002
2301,300.0,2313.32,879.76,3.28,41224.11,377381.28,2.6555,76450.78,658.30,Sounding_Rocket,M-002
2302,301.0,1452.97,847.38,3.32,41224.11,381653.55,2.5320,85044.99,636.06,Sounding_Rocket,M-002
2303,302.0,624.98,814.70,3.34,41224.11,382707.58,2.4112,94038.72,614.41,Sounding_Rocket,M-002

,Time,Altitude,Velocity,Accel,Mass,Dyn. Pressure,Mach,Atm. Pressure,Stag. Temp,Flight_Type,Mission_ID
2304,0.0,0.00,0.00,0.80,421300.00,0.00,0.0000,101325.00,288.15,Early_Engine_Shutdown,M-003
2305,1.0,3.95,7.93,0.82,417934.01,38.48,0.0233,101277.53,288.16,Early_Engine_Shutdown,M-003
2306,2.0,15.90,16.00,0.83,414568.74,156.53,0.0470,101134.10,288.17,Early_Engine_Shutdown,M-003
2307,3.0,36.00,24.21,0.85,411204.91,357.90,0.0712,100893.31,288.21,Early_Engine_Shutdown,M-003
2308,4.0,64.38,32.58,0.86,407843.26,646.07,0.0958,100553.96,288.26,Early_Engine_Shutdown,M-003
...,...,...,...,...,...,...,...,...,...,...,...
2423,119.0,1921.49,445.20,0.85,308013.14,100535.19,1.3376,80272.96,374.30,Early_Engine_Shutdown,M-003
2424,120.0,1475.80,453.38,0.84,308013.14,109007.35,1.3551,84807.22,380.86,Early_Engine_Shutdown,M-003
2425,121.0,1021.90,461.43,0.82,308013.14,118093.09,1.3719,89635.92,387.47,Early_Engine_Shutdown,M-003
2426,122.0,559.93,469.35,0.81,308013.14,127825.13,1.3881,94776.73,394.14,Early_Engine_Shutdown,M-003
2427,123.0,90.03,477.13,0.79,308013.14,138236.23,1.4035,100248.14,400.86,Early_Engine_Shutdown,M-003

In [2]:

# %%
display (telemetriadados.info())
telemetriadados = telemetriadados.dropna()
display(telemetriadados.info())
display(telemetriadados)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2428 entries, 0 to 2427
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Time           2428 non-null   float64
 1   Altitude       2428 non-null   float64
 2   Velocity       2428 non-null   float64
 3   Accel          2428 non-null   float64
 4   Mass           2428 non-null   float64
 5   Dyn. Pressure  2428 non-null   float64
 6   Mach           2428 non-null   float64
 7   Atm. Pressure  2428 non-null   float64
 8   Stag. Temp     2428 non-null   float64
 9   Flight_Type    2428 non-null   object
 10  Mission_ID     2428 non-null   object
dtypes: float64(9), object(2)
memory usage: 208.8+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2428 entries, 0 to 2427
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Time           2428 non-null   float64
 1   Altitude       2428 non-null   float64
 2   Velocity       2428 non-null   float64
 3   Accel          2428 non-null   float64
 4   Mass           2428 non-null   float64
 5   Dyn. Pressure  2428 non-null   float64
 6   Mach           2428 non-null   float64
 7   Atm. Pressure  2428 non-null   float64
 8   Stag. Temp     2428 non-null   float64
 9   Flight_Type    2428 non-null   object
 10  Mission_ID     2428 non-null   object
dtypes: float64(9), object(2)
memory usage: 208.8+ KB

None

,Time,Altitude,Velocity,Accel,Mass,Dyn. Pressure,Mach,Atm. Pressure,Stag. Temp,Flight_Type,Mission_ID
0,0.0,0.00,0.00,0.80,421300.00,0.00,0.0000,101325.00,288.15,Heavy_Lift_Standard,M-001
1,1.0,3.95,7.93,0.82,417934.01,38.48,0.0233,101277.53,288.16,Heavy_Lift_Standard,M-001
2,2.0,15.90,16.00,0.83,414568.74,156.53,0.0470,101134.10,288.17,Heavy_Lift_Standard,M-001
3,3.0,36.00,24.21,0.85,411204.91,357.90,0.0712,100893.31,288.21,Heavy_Lift_Standard,M-001
4,4.0,64.38,32.58,0.86,407843.26,646.07,0.0958,100553.96,288.26,Heavy_Lift_Standard,M-001
...,...,...,...,...,...,...,...,...,...,...,...
2423,119.0,1921.49,445.20,0.85,308013.14,100535.19,1.3376,80272.96,374.30,Early_Engine_Shutdown,M-003
2424,120.0,1475.80,453.38,0.84,308013.14,109007.35,1.3551,84807.22,380.86,Early_Engine_Shutdown,M-003
2425,121.0,1021.90,461.43,0.82,308013.14,118093.09,1.3719,89635.92,387.47,Early_Engine_Shutdown,M-003
2426,122.0,559.93,469.35,0.81,308013.14,127825.13,1.3881,94776.73,394.14,Early_Engine_Shutdown,M-003
2427,123.0,90.03,477.13,0.79,308013.14,138236.23,1.4035,100248.14,400.86,Early_Engine_Shutdown,M-003

In [3]:

# %%
display (telemetriadados.columns)
telemetriadados1 = telemetriadados1.sort_values (by= "Time", ascending=True)
telemetriadados2 = telemetriadados2.sort_values (by= "Time", ascending=True)
telemetriadados3 = telemetriadados3.sort_values (by= "Time", ascending=True)

telemetriadados1 = telemetriadados1.drop (columns = ["Flight_Type", "Mission_ID"])
telemetriadados2 = telemetriadados2.drop (columns = ["Flight_Type", "Mission_ID"])
telemetriadados3 = telemetriadados3.drop (columns = ["Flight_Type", "Mission_ID"])




for dado in telemetriadados1:
    if dado != "Time":
        gráficos1 = px.line(telemetriadados1, x= "Time", y= dado, title= "Telemetria de voo1")
        gráficos1.show()
display (telemetriadados1)


for dado in telemetriadados2:
    if dado != "Time":
        gráficos2 = px.line(telemetriadados2, x= "Time", y= dado, title= "Telemetria de voo2")
        gráficos2.show()
display (telemetriadados2)


for dado in telemetriadados3:
    if dado != "Time":
        gráficos3 = px.line(telemetriadados3, x= "Time", y= dado, title= "Telemetria de voo3")
        gráficos3.show()
display (telemetriadados3)

Index(['Time', 'Altitude', 'Velocity', 'Accel', 'Mass', 'Dyn. Pressure',
       'Mach', 'Atm. Pressure', 'Stag. Temp', 'Flight_Type', 'Mission_ID'],
      dtype='object')

,Time,Altitude,Velocity,Accel,Mass,Dyn. Pressure,Mach,Atm. Pressure,Stag. Temp
0,0.0,0.00,0.00,0.80,421300.00,0.00,0.0000,101325.00,288.15
1,1.0,3.95,7.93,0.82,417934.01,38.48,0.0233,101277.53,288.16
2,2.0,15.90,16.00,0.83,414568.74,156.53,0.0470,101134.10,288.17
3,3.0,36.00,24.21,0.85,411204.91,357.90,0.0712,100893.31,288.21
4,4.0,64.38,32.58,0.86,407843.26,646.07,0.0958,100553.96,288.26
...,...,...,...,...,...,...,...,...,...
1996,1996.0,1776351.04,3965.36,0.61,25506.96,0.00,0.0000,0.00,216.65
1997,1997.0,1772834.62,3970.69,0.61,25506.96,0.00,0.0000,0.00,216.65
1998,1998.0,1769312.61,3976.02,0.61,25506.96,0.00,0.0000,0.00,216.65
1999,1999.0,1765785.00,3981.35,0.61,25506.96,0.00,0.0000,0.00,216.65
2000,2000.0,1762251.78,3986.69,0.61,25506.96,0.00,0.0000,0.00,216.65

,Time,Altitude,Velocity,Accel,Mass,Dyn. Pressure,Mach,Atm. Pressure,Stag. Temp
2001,0.0,0.00,0.00,1.79,85600.00,0.00,0.0000,101325.00,288.15
2002,1.0,8.82,17.69,1.82,84542.33,191.44,0.0520,101219.15,288.25
2003,2.0,35.48,35.71,1.85,83485.06,778.37,0.1050,100899.44,288.55
2004,3.0,80.34,54.07,1.89,82428.59,1776.64,0.1590,100363.51,289.08
2005,4.0,143.73,72.75,1.92,81373.32,3197.48,0.2141,99610.25,289.85
...,...,...,...,...,...,...,...,...,...
2299,298.0,4128.83,942.18,3.07,41224.11,358652.83,2.9074,60612.02,703.09
2300,299.0,3205.55,911.49,3.19,41224.11,369725.66,2.7810,68294.95,680.78
2301,300.0,2313.32,879.76,3.28,41224.11,377381.28,2.6555,76450.78,658.30
2302,301.0,1452.97,847.38,3.32,41224.11,381653.55,2.5320,85044.99,636.06
2303,302.0,624.98,814.70,3.34,41224.11,382707.58,2.4112,94038.72,614.41

,Time,Altitude,Velocity,Accel,Mass,Dyn. Pressure,Mach,Atm. Pressure,Stag. Temp
2304,0.0,0.00,0.00,0.80,421300.00,0.00,0.0000,101325.00,288.15
2305,1.0,3.95,7.93,0.82,417934.01,38.48,0.0233,101277.53,288.16
2306,2.0,15.90,16.00,0.83,414568.74,156.53,0.0470,101134.10,288.17
2307,3.0,36.00,24.21,0.85,411204.91,357.90,0.0712,100893.31,288.21
2308,4.0,64.38,32.58,0.86,407843.26,646.07,0.0958,100553.96,288.26
...,...,...,...,...,...,...,...,...,...
2423,119.0,1921.49,445.20,0.85,308013.14,100535.19,1.3376,80272.96,374.30
2424,120.0,1475.80,453.38,0.84,308013.14,109007.35,1.3551,84807.22,380.86
2425,121.0,1021.90,461.43,0.82,308013.14,118093.09,1.3719,89635.92,387.47
2426,122.0,559.93,469.35,0.81,308013.14,127825.13,1.3881,94776.73,394.14
2427,123.0,90.03,477.13,0.79,308013.14,138236.23,1.4035,100248.14,400.86

In [4]:


# %%
# define a função com uma fonte de dados indefinida ainda e um texto compatível indefinido (df-ID, ID)
def telemetrycalc (df_ID, ID):
    print("Resultado:", ID)
    massainicial= df_ID["Mass"].max()
    massafinal = df_ID ["Mass"].min()

    gasto_propelente = massainicial - massafinal
    payload = massafinal
    print ("A carga payload adjunta do restante do hardware foi de", payload, "kg")
    print ("O propelente gasto em kg foi de", gasto_propelente, "kg")
    velocidade_max = df_ID ["Velocity"].max()
    print ("A máxima velocidade do foguete foi", velocidade_max, "m/s, ou", velocidade_max / 1000, "km/s")

    velocidade_min = df_ID ["Velocity"].min()

    deltav = velocidade_max - velocidade_min

    print ("O delta V foi de", deltav, "m/s")

    highest_temp = df_ID["Stag. Temp"].max()
    temp_celsius = (highest_temp - 32) * 0.555555556
    print (highest_temp, "Fahrenheit foi a máxima temperatura, em celsius equivale a:", temp_celsius)

    df_ID ["forcaG"] = df_ID["Accel"] / 9.81

    # display (df_ID) pra mostrar a tabela de cada base de dados separada anteriormente

    print("A máxima força G sofrida pelo hardware foi de:",df_ID["forcaG"].max())

    maxQ = df_ID["Dyn. Pressure"].max()
    print ("A máxima pressão aerodinâmica em pascais do voo do hardware foi", maxQ, "Pa")
    print("=====================================================================")
# todos os textos anteriores não definem a base de dados e o texto compativel delas, só definem a função a ser executada pelo python

telemetrycalc(telemetriadados1, "M-001")
telemetrycalc(telemetriadados2, "M-002")
telemetrycalc(telemetriadados3, "M-003")
# indica a base de dados e o texto compativel a ser executado na função pré-definida quantas vezes e por quantas bases de dados separadas você desejar

Resultado: M-001
A carga payload adjunta do restante do hardware foi de 25506.96 kg
O propelente gasto em kg foi de 395793.04 kg
A máxima velocidade do foguete foi 6257.69 m/s, ou 6.257689999999999 km/s
O delta V foi de 6257.69 m/s
4263.92 Fahrenheit foi a máxima temperatura, em celsius equivale a: 2351.06666854752
A máxima força G sofrida pelo hardware foi de: 2.9347604485219163
A máxima pressão aerodinâmica em pascais do voo do hardware foi 55236.14 Pa
=====================================================================
Resultado: M-002
A carga payload adjunta do restante do hardware foi de 41224.11 kg
O propelente gasto em kg foi de 44375.89 kg
A máxima velocidade do foguete foi 1165.69 m/s, ou 1.1656900000000001 km/s
O delta V foi de 1165.69 m/s
892.91 Fahrenheit foi a máxima temperatura, em celsius equivale a: 478.28333371595994
A máxima força G sofrida pelo hardware foi de: 0.4607543323139653
A máxima pressão aerodinâmica em pascais do voo do hardware foi 382707.58 Pa
=====================================================================
Resultado: M-003
A carga payload adjunta do restante do hardware foi de 308013.14 kg
O propelente gasto em kg foi de 113286.85999999999 kg
A máxima velocidade do foguete foi 477.13 m/s, ou 0.47713 km/s
O delta V foi de 477.13 m/s
400.86 Fahrenheit foi a máxima temperatura, em celsius equivale a: 204.92222238616
A máxima força G sofrida pelo hardware foi de: 0.1396534148827727
A máxima pressão aerodinâmica em pascais do voo do hardware foi 138236.23 Pa
=====================================================================