In [ ]:
import pandas as pd
import plotly.express as px

#read the csv selecting the especific coulmns with the 'usecols' 
thrust_telemetry = pd.read_csv("thrust_curve.csv", usecols=["Tempo", "Empuxo"])
display(thrust_telemetry)
display(thrust_telemetry.info())

thrust_telemetry = thrust_telemetry.dropna()

display(thrust_telemetry.info())
display(thrust_telemetry)

    Tempo  Empuxo
0    0.00     0.0
1    0.02   150.5
2    0.05   380.2
3    0.08   422.0
4    0.15   350.8
5    0.50   285.4
6    1.00   275.0
7    1.50   270.6
8    2.00   265.1
9    2.40   250.3
10   2.60   120.0
11   2.75    45.5
12   2.85     0.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Tempo   13 non-null     float64
 1   Empuxo  13 non-null     float64
dtypes: float64(2)
memory usage: 340.0 bytes

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Tempo   13 non-null     float64
 1   Empuxo  13 non-null     float64
dtypes: float64(2)
memory usage: 340.0 bytes

None

    Tempo  Empuxo
0    0.00     0.0
1    0.02   150.5
2    0.05   380.2
3    0.08   422.0
4    0.15   350.8
5    0.50   285.4
6    1.00   275.0
7    1.50   270.6
8    2.00   265.1
9    2.40   250.3
10   2.60   120.0
11   2.75    45.5
12   2.85     0.0

In [13]:
display (thrust_telemetry.columns)

for data in thrust_telemetry:
    if data != "Tempo":
        grafic1 = px.line(thrust_telemetry, x = "Tempo", y = "Empuxo", title = "Thrust Curve")
        grafic1.show()
display (thrust_telemetry)

Index(['Tempo', 'Empuxo'], dtype='object')

    Tempo  Empuxo
0    0.00     0.0
1    0.02   150.5
2    0.05   380.2
3    0.08   422.0
4    0.15   350.8
5    0.50   285.4
6    1.00   275.0
7    1.50   270.6
8    2.00   265.1
9    2.40   250.3
10   2.60   120.0
11   2.75    45.5
12   2.85     0.0

In [ ]:
import numpy as np

while True:

    def thrust_calc (df_ID, ID):
        print ("Analysing column:", ID)
        Max_Thrust = df_ID[ID].max()
        Min_Thrust = df_ID[ID].min()
        

        print("Your max Thrust was:", Max_Thrust, "Newtons")
        print("Your min Thrust was:", Min_Thrust, "Newtons")
    #redefine a sua base de dados relativo a variavel thrust_telemetry
    thrust_telemetry = pd.read_csv("thrust_curve.csv")
    #dá definição ao ID 
    thrust_calc(thrust_telemetry, "Empuxo")

    g = 9.81
    ISP = float(input("What is your engine ISP in seconds? Write right here:"))
    ve = g * ISP
    
    mass_flow = thrust_telemetry["Empuxo"] /ve
    grafic2 = px.line(x = thrust_telemetry["Tempo"], y = mass_flow, title = "Mass flow trough the flight in kg/s")
    grafic2.show()
    grafic1.show()
    #a função trapezoid integra o gráfico segundo os eixos que você seleciona pelo thrust_telemetry dividindo o gráfico em n trapezios e integrando
    It = np.trapezoid(y = thrust_telemetry["Empuxo"], x = thrust_telemetry["Tempo"])
    print("Your Total Impulse is:", It, "N*s")
    rerun =  input("If you want to rerun your calculator with another Thrust test data press 'S', if don't press 'N'.")
    if rerun.upper() == "N":
        break

Analysing column: Empuxo
Your max Thrust was: 422.0 Newtons
Your min Thrust was: 0.0 Newtons

Your Total Impulse is: 725.1040000000002 N*s